"""Initial schema

Revision ID: 5a1e0b55ed63
Revises: 
Create Date: 2025-12-19 11:16:14.757105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a1e0b55ed63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('homeowner_name', sa.String(length=255), nullable=True),
    sa.Column('homeowner_email', sa.String(length=255), nullable=True),
    sa.Column('homeowner_phone', sa.String(length=50), nullable=True),
    sa.Column('homeowner_email_sent', sa.Boolean(), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('accepted_tier', sa.String(length=10), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('brief_scope', sa.Text(), nullable=True),
    sa.Column('full_estimate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('renovation_vision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_image_url', sa.Text(), nullable=True),
    sa.Column('homeowner_marked_complete', sa.Boolean(), nullable=False),
    sa.Column('contractor_marked_complete', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('idx_marketplace', 'projects', ['status', 'zip_code', 'project_type', 'total_price'], unique=False)
    op.create_index(op.f('ix_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_token'), 'projects', ['token'], unique=True)
    op.create_index(op.f('ix_projects_zip_code'), 'projects', ['zip_code'], unique=False)
    op.create_table('conversation_states',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index('idx_conversation_updated', 'conversation_states', ['updated_at'], unique=False)
    op.create_table('llm_costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_costs_date', 'llm_costs', ['created_at'], unique=False)
    op.create_index('idx_llm_costs_model', 'llm_costs', ['model'], unique=False)
    op.create_index('idx_llm_costs_project', 'llm_costs', ['project_id'], unique=False)
    op.create_index(op.f('ix_llm_costs_created_at'), 'llm_costs', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_costs_model'), 'llm_costs', ['model'], unique=False)
    op.create_index(op.f('ix_llm_costs_project_id'), 'llm_costs', ['project_id'], unique=False)
    op.create_table('unlocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('unlock_token', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('contractor_email', sa.String(length=255), nullable=False),
    sa.Column('contractor_name', sa.String(length=255), nullable=True),
    sa.Column('contractor_phone', sa.String(length=50), nullable=True),
    sa.Column('contractor_company', sa.String(length=255), nullable=True),
    sa.Column('contractor_details_saved', sa.Boolean(), nullable=False),
    sa.Column('contractor_email_sent', sa.Boolean(), nullable=False),
    sa.Column('homeowner_notified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contractor_email', 'unlocks', ['contractor_email'], unique=False)
    op.create_index('idx_payment_id', 'unlocks', ['payment_id'], unique=False)
    op.create_index('idx_unlock_token', 'unlocks', ['unlock_token'], unique=False)
    op.create_index(op.f('ix_unlocks_contractor_email'), 'unlocks', ['contractor_email'], unique=False)
    op.create_index(op.f('ix_unlocks_payment_id'), 'unlocks', ['payment_id'], unique=False)
    op.create_index(op.f('ix_unlocks_project_id'), 'unlocks', ['project_id'], unique=False)
    op.create_index(op.f('ix_unlocks_unlock_token'), 'unlocks', ['unlock_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unlocks_unlock_token'), table_name='unlocks')
    op.drop_index(op.f('ix_unlocks_project_id'), table_name='unlocks')
    op.drop_index(op.f('ix_unlocks_payment_id'), table_name='unlocks')
    op.drop_index(op.f('ix_unlocks_contractor_email'), table_name='unlocks')
    op.drop_index('idx_unlock_token', table_name='unlocks')
    op.drop_index('idx_payment_id', table_name='unlocks')
    op.drop_index('idx_contractor_email', table_name='unlocks')
    op.drop_table('unlocks')
    op.drop_index(op.f('ix_llm_costs_project_id'), table_name='llm_costs')
    op.drop_index(op.f('ix_llm_costs_model'), table_name='llm_costs')
    op.drop_index(op.f('ix_llm_costs_created_at'), table_name='llm_costs')
    op.drop_index('idx_llm_costs_project', table_name='llm_costs')
    op.drop_index('idx_llm_costs_model', table_name='llm_costs')
    op.drop_index('idx_llm_costs_date', table_name='llm_costs')
    op.drop_table('llm_costs')
    op.drop_index('idx_conversation_updated', table_name='conversation_states')
    op.drop_table('conversation_states')
    op.drop_index(op.f('ix_projects_zip_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_token'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_type'), table_name='projects')
    op.drop_index('idx_marketplace', table_name='projects')
    op.drop_index('idx_created_at', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###

